[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
plan_vault = "3TePuiM6kKgQeUb6YGbybDN1WN22x5Yi15xxoGavn5gQ"

[programs.devnet]
plan_vault = "3TePuiM6kKgQeUb6YGbybDN1WN22x5Yi15xxoGavn5gQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest --reporter verbose"
