name = "plan-vault-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "plan-vault-db"
database_id = "d0394760-014b-4585-b826-f4316e3ec82d"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "plan-vault-images"

[vars]
JWT_SECRET = "replace-with-generated-secret"
CORS_ORIGIN = "https://trading-plan-vault.indralukmana.workers.dev"
